// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrfKwNVyV5pfFz2TGCH8ueorcFrgV4b3E',
    appId: '1:1058866964717:web:46ba7a43621b102384c4e4',
    messagingSenderId: '1058866964717',
    projectId: 'scal-20c71',
    authDomain: 'scal-20c71.firebaseapp.com',
    storageBucket: 'scal-20c71.appspot.com',
    measurementId: 'G-MJ26BTS4E3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMPHoR5NwXo_nY4sStNfDmhm-TEKDybko',
    appId: '1:1058866964717:android:7c99f2b44c8dda9684c4e4',
    messagingSenderId: '1058866964717',
    projectId: 'scal-20c71',
    storageBucket: 'scal-20c71.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeEeQHrxLZ2VSjkMoVGIMCpvuSp8bmdkU',
    appId: '1:1058866964717:ios:90aa21e9065b20eb84c4e4',
    messagingSenderId: '1058866964717',
    projectId: 'scal-20c71',
    storageBucket: 'scal-20c71.appspot.com',
    iosBundleId: 'com.wakizaka24.scal',
  );

}